# cloud-init.yml
#cloud-config
packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common

runcmd:
  - curl -s https://launchpad.net/~ansible/+archive/ubuntu/ansible | tee /etc/apt/sources.list.d/ansible.list
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
  - apt-get update
  - apt-get install -y ansible
  - ansible --version  # Verify installation
