---
- name: Restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes

- name: Initialize Kubernetes Master Node
  become: true
  when: hostvars[inventory_hostname].is_master
  command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --node-name={{ hostvars[inventory_hostname].node_name }}"
  register: kubeadm_init

- name: Create .kube directory for user on master
  become: true
  when: hostvars[inventory_hostname].is_master
  file:
    path: /home/azureadmin/.kube
    state: directory
    owner: azureadmin
    group: azureadmin
    mode: '0755'

- name: Set up kubeconfig for user on master
  when: hostvars[inventory_hostname].is_master
  copy:
    content: "{{ kubeadm_init.stdout_lines | join('\n') }}"
    dest: /home/azureadmin/.kube/config
    owner: azureadmin
    group: azureadmin
    mode: '0644'

- name: Install Flannel CNI (Container Network Interface) plugin
  when: hostvars[inventory_hostname].is_master
  command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
  register: flannel
  retries: 5
  delay: 10
